version: "3.1"
services:
  app:
    image: nawrasprogressoft/api-project:1.0
    restart: always
    ports:
      - 3000:3000
  redis:
    image: redis
    ports:
      - 6379:6379
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: 56035fd19aad482489b
      MONGO_INITDB_DATABASE: apiDb
